= Jakarta Batch TCK Reference Guide
:toc:
:sectnums:

== Preface

This guide describes how to download, install, configure, and run the Technology Compatibility Kit (TCK) used to verify the compatibility of an implementation of the Jakarta Batch specification.

=== Licensing
The Jakarta Batch TCK is provided under the 
*Eclipse Foundation Technology Compatibility Kit License - v 1.0* [https://www.eclipse.org/legal/tck.php].

=== Who Should Use This Guide
This guide is for implementers of the Jakarta Batch specification, to assist in running the test suite that verifies the compatibility of their implementation.

=== Before You Read This Guide
Before reading this guide, you should familiarize yourself with the Jakarta Batch specification.

Information about the specification, including links to the specification documents, can be found on the Jakarta Batch project home page [https://projects.eclipse.org/projects/ee4j.batch] and also at the GitHub repository home  [https://github.com/eclipse-ee4j/batch-api].

== Introduction
The Jakarta Batch TCK tests implementations of the Jakarta Batch specification, which describes the job specification language, Java programming model, and runtime environment for Jakarta Batch applications.

=== What Tests Do I Need To Pass (to pass the TCK)?  

As an overview, note in order to pass the Jakarta Batch TCK you must run against your implementation, passing 100% of both the:

•	Signature Tests
•	TestNG Test Suite

The two types of tests are not encapsulated in a single execution task or command; they must be executed separately from each other and each must be executed separately for each version of Java tested (e.g. Java 8, etc.). 

= TCK Challenges/Appeals Process
The "Jakarta EE TCK Process 1.0" will govern all process details used for challenges to the Jakarta Batch TCK.    

Except from the "Jakarta EE TCK Process 1.0":

> Specifications are the sole source of truth and considered overruling to the TCK in all senses. In the course of implementing a specification and attempting to pass the TCK, implementations may come to the conclusion that one or more tests or assertions do not conform to the specification and therefore MUST be excluded from the certification requirements.
> 
> Requests for tests to be excluded are referred to as Challenges.  This section identifies who can make challenges to the TCK, what challenges to the TCK may be submitted, how these challenges are submitted, how and to whom challenges are addressed.

Current link to https://docs.google.com/document/d/1Et3LtK-2SUuAoOV56t8R8fKnRWhbWqg9SLgm-VhbDPY/edit#heading=h.m0w944vn2kbp[Jakarta EE TCK Process 1.0 - Challenges]:

= Certification of Compatibility